### ISSUE TITLE
[BUG] Cannot connect to hidden wifi

### ISSUE THREAD

**Issue by anoniono** [Ultramarine-Linux/ultramarine#11] opened 2022-09-19 03:58 UTC
**Describe the bug**
Cannot connect to hidden wifi on pantheon edition.
When try to connect, wifi icon blink for sometime and stops.

**To Reproduce**
Set up a hidden WIFI (5G in my case).
Connect, it won't.

**Expected behavior**
Connect & auto reconnect

**Logs**
<details><summary>journalct log</summary>
<p>

```
Sep 19 11:12:25 fedora systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
Sep 19 11:12:25 fedora systemd[1]: Started systemd-hostnamed.service - Hostname Service.
Sep 19 11:12:25 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 19 11:12:30 fedora io.elementary.w[2030]: Device.vala:190: Updating the upower device parameters failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Refresh is not implemented on interface org.freedesktop.UPower.Device
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9012] device (wlp3s0): Activation: starting connection '5g-hidden' (7794c895-4b8b-4b84-95ba-8f201d9af96a)
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9015] audit: op="connection-activate" uuid="7794c895-4b8b-4b84-95ba-8f201d9af96a" name="5g-hidden" pid=2030 uid=1000 result="success"
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9017] device (wlp3s0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9020] manager: NetworkManager state is now CONNECTING
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9028] device (wlp3s0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9031] device (wlp3s0): Activation: (wifi) access point '5g-hidden' has security, but secrets are required.
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9032] device (wlp3s0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9055] device (wlp3s0): state change: need-auth -> prepare (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9058] device (wlp3s0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9062] device (wlp3s0): Activation: (wifi) connection '5g-hidden' has security, and secrets exist.  No new secrets needed.
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9062] Config: added 'ssid' value '5g-hidden'
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9062] Config: added 'scan_ssid' value '1'
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9063] Config: added 'bgscan' value 'simple:30:-70:86400'
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9063] Config: added 'key_mgmt' value 'WPA-PSK WPA-PSK-SHA256'
Sep 19 11:12:32 fedora NetworkManager[1006]: <info>  [1663557152.9063] Config: added 'psk' value '<hidden>'
Sep 19 11:12:35 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:36 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:37 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:38 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:39 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:40 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:41 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:42 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:43 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:44 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:45 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:46 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:47 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:48 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:49 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:50 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:51 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:52 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:53 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:54 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:55 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:56 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
Sep 19 11:12:57 fedora NetworkManager[1006]: <warn>  [1663557177.8300] device (wlp3s0): Activation: (wifi) association took too long, failing activation
Sep 19 11:12:57 fedora NetworkManager[1006]: <info>  [1663557177.8302] device (wlp3s0): state change: config -> failed (reason 'ssid-not-found', sys-iface-state: 'managed')
Sep 19 11:12:57 fedora wpa_supplicant[791]: wlp3s0: CTRL-EVENT-DSCP-POLICY clear_all
Sep 19 11:12:57 fedora NetworkManager[1006]: <info>  [1663557177.8313] manager: NetworkManager state is now DISCONNECTED
Sep 19 11:12:57 fedora NetworkManager[1006]: <warn>  [1663557177.8322] device (wlp3s0): Activation: failed for connection '5g-hidden'
Sep 19 11:12:57 fedora NetworkManager[1006]: <info>  [1663557177.8329] device (wlp3s0): state change: failed -> disconnected (reason 'none', sys-iface-state: 'managed')
Sep 19 11:12:59 fedora systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Sep 19 11:12:59 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 19 11:12:59 fedora audit: BPF prog-id=0 op=UNLOAD
Sep 19 11:12:59 fedora audit: BPF prog-id=0 op=UNLOAD
Sep 19 11:13:00 fedora io.elementary.w[2030]: Device.vala:190: Updating the upower device parameters failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Refresh is not implemented on interface org.freedesktop.UPower.Device
Sep 19 11:13:01 fedora NetworkManager[1006]: <info>  [1663557181.9639] device (wlp3s0): supplicant interface state: disconnected -> inactive
Sep 19 11:13:30 fedora io.elementary.w[2030]: Device.vala:190: Updating the upower device parameters failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Refresh is not implemented on interface org.freedesktop.UPower.Device
Sep 19 11:13:52 fedora systemd[1]: Starting systemd-tmpfiles-clean.service - Cleanup of Temporary Directories...
Sep 19 11:13:52 fedora systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Sep 19 11:13:52 fedora systemd[1]: Finished systemd-tmpfiles-clean.service - Cleanup of Temporary Directories.
```

</p>
</details>

**Desktop:**
 - OS: Ultramarine Linux Pantheon Edition
 - Version: F36

**Additional context**
on elementryOS 6.1: Can connect to hidden wifi. But auto reconnect doesn't work. Need manual connect everytime.

**Comment by trobonox** [comment] 2022-09-20 19:35
If you haven't done it already, please report a bug report to elementaryOS since this seems to be mostly their issue. After that we will be able to investigate this further and see if this is also caused by any issues on our side.

**Comment by nothingneko** [comment] 2023-04-11 21:30
This appears to be resolved in Ultramarine 37. Are you still having this issue?

**Closed** 2023-11-26 10:18 UTC
Labels: bug
